#!/usr/bin/env bash 
# transfers a file from our client to a server

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

# Use scp to transfer the file to the server's home directory
scp -o  StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~

# Check if scp was successful
#if [ $? -eq 0 ]; then
#    echo "File transfer successful."
#else
#    echo "File transfer failed."
#fi
