#!/usr/bin/env bash

#this script is to debug webstack

apt-get update
apt-get install -y nginx

#modify nginmx configuration to listen to port 80 
sed -i  's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default


#restart nginx 
service nginx restart

