#!/usr/bin/env bash

#this script is to debug webstack

apt-get update
apt-get install -y nginx

#modify nginmx configuration to listen to port 80 
rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx 
service nginx restart

