#!/usr/bin/env bash

# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory pat
#this is a strimgf 
while read passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
