#!/usr/bin/env bash
#this is a strimgf 
while IFS=: read username x uid gid comment home shell; do
	echo "Username: $username"
	echo "User ID: $uid"
	echo "Home Directory: $home"
	echo
done < /etc/passwd
