#!/usr/bin/env bash
#tell the story of reading  paswd using while 
IFS=":"

while read user_id passwd uid gid gcos home shell;
do
	echo "The user $USERNAME is part of the $gid gang, "\
	"lives in $home  and rides $shell."\ 
	"$uid's place is protected by the passcode $password,"\
	"more info about the user here: $info"   
done < "/etc/passwd"

