#!/usr/bin/env bash

# Stop the Nginx service if it is running
service nginx stop

# Update the Nginx configuration file to run as the nginx user
sed -i 's/user\s*[^;]*/user nginx;/g' /etc/nginx/nginx.conf

# Update the Nginx configuration file to listen on all active IPs on port 8080
sed -i 's/listen\s*[^;]*;/listen 8080;/g' /etc/nginx/nginx.conf

# Start the Nginx service
service nginx start

